openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /api/ping:
    get:
      summary: Ping
      operationId: ping_api_ping_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Ping Api Ping Get
                type: array
                items:
                  $ref: '#/components/schemas/Response'
components:
  schemas:
    Response:
      title: Response
      required:
      - resp
      type: object
      properties:
        resp:
          title: Resp
          type: string
