env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - unused-imports
rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".ts"
    - ".tsx"
  react/function-component-definition:
    - 2
    - namedComponents: arrow-function
  unused-imports/no-unused-imports-ts: warn
  sort-imports: off
  import/order:
    - warn
    - 
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  react/require-default-props: off
  no-empty-pattern: off
  react/no-array-index-key: off
  no-mixed-operators: off
  react/jsx-no-useless-fragment: off
  react/jsx-props-no-spreading: off
  no-param-reassign: off
  no-bitwise: off
  no-promise-executor-return: off
  "@typescript-eslint/comma-dangle": off
  import/no-default-export: warn
  import/prefer-default-export: off
  no-nested-ternary: off
  react/destructuring-assignment: off
  react/prop-types: off
