/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseModel
 */
export interface ResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ResponseModel
     */
    resp: string;
}

/**
 * Check if a given object implements the ResponseModel interface.
 */
export function instanceOfResponseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "resp" in value;

    return isInstance;
}

export function ResponseModelFromJSON(json: any): ResponseModel {
    return ResponseModelFromJSONTyped(json, false);
}

export function ResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resp': json['resp'],
    };
}

export function ResponseModelToJSON(value?: ResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resp': value.resp,
    };
}

